# Generated by Django 3.2 on 2021-07-20 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('slug', models.SlugField()),
                ('body', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('post_img', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
            ],
            options={
                'ordering': ('-date_created',),
                'index_together': {('id', 'slug')},
            },
        ),
    ]
